# Generated by Django 4.1.7 on 2026-02-09 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('duration', models.IntegerField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'activities',
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=200)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['-total_points'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('captain_id', models.CharField(blank=True, max_length=100, null=True)),
                ('member_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('fitness_level', models.CharField(blank=True, max_length=50)),
                ('team_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('calories_estimate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workouts',
            },
        ),
    ]
